# Generated by Django 4.2.3 on 2023-07-31 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Engine",
            fields=[
                (
                    "engine_number",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ShowRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name_plural": "Showrooms",
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("pics", models.ImageField(blank=True, null=True, upload_to="")),
                ("role", models.CharField(max_length=100)),
                (
                    "showroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="car_showroom.showroom",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Staff",
            },
        ),
        migrations.CreateModel(
            name="Model",
            fields=[
                ("name", models.CharField(max_length=100)),
                (
                    "engine",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="car_showroom.engine",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="car_showroom.brand",
                    ),
                ),
                ("features", models.ManyToManyField(to="car_showroom.feature")),
            ],
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "chassis_number",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="car_showroom.model",
                    ),
                ),
            ],
        ),
    ]
