# Generated by Django 4.2.3 on 2023-07-31 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_showroom", "0002_alter_showroom_options_engine_name_engine_specs"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="stock",
            field=models.IntegerField(default=0),
        ),
    ]
